[Fix #13372] Fix inconsistent cache directory when using --cache-root
rubocop/rubocop pull request #13405
Opened 2024-10-31 21:35 UTC by Capncavedan

Fixes #13372.

This PR fixes inconsistent cache directory calculation during cache pruning when the --cache-root option is used instead of ENV or YAML configuration.

In this work, I renamed method arguments and local variables to try to better distinguish between "cache root", e.g. `.cache`, and "cache working directory", e.g. `.cache/rubocop_cache`.

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

2024-11-28 07:29 UTC, bbatsov commented
Looks good to me overall, although I'm not sure about the name choices. Perhaps we should at least document them somewhere in the code as before reading the description of the PR I wasn't sure what the `cache_working_directory` was. @jonas054 Any thoughts from you?

2024-11-28 18:38 UTC, jonas054 commented
It looks good to me too. I agree that something could be done to improve the naming. @Capncavedan How about changing `cache_working_dir` to `rubocop_cache_dir`? Connecting the variable name to the actual directory name `rubocop_cache` should make it easier to grasp.

2024-11-29 17:01 UTC, jonas054 requested changes
It looks good to me too. I agree that something could be done to improve the naming. @Capncavedan How about changing `cache_working_dir` to `rubocop_cache_dir`? Connecting the variable name to the actual directory name `rubocop_cache` should make it easier to grasp.

2024-12-10 23:59 UTC, Capncavedan commented
@jonas054 done!

2025-01-15 08:00 UTC, merged