[Fix #9373]Fix  indentation style tabs infinite loop
rubocop/rubocop pull request #9377
Opened 2021-01-14 18:53 UTC by joeyparis

This fixes the bug described in #9373.

However, the testing for this cop breaks as it designed to replace every 2 spaces, with 1 tab but the fix replaces every 1 space with 1 tab. I would say this is a problem with the fix, but replacing 2 spaces only works in the vacuum of the test and leads to an infinite loop when used along with other cops.

When combined with `Layout/IndentationWidth` replacing every 1 space with a tab still leads to proper indentation by the time all the cops are done. But I'm assuming this is not ideal behavior for one to have to rely on another like that.

I'm not sure what the proper steps are to finalize this. Do I update the tests to just replace every 1 space with 1 tab? Or should we dive deeper into what else is contributing to the infinite loop?

-----------------

Before submitting the PR make sure the following are checked:

* [*] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [*] Wrote [good commit messages][1].
* [*] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [*] Feature branch is up-to-date with `master` (if not - rebase it).
* [ ] Squashed related commits together.
* [ ] Added tests.
* [ ] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [*] Added an entry (file) to the [changelog folder](https://github.com/rubocop-hq/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop-hq/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

2021-02-15 07:25 UTC, bbatsov commented
@jonas054 Please, take a look here when you can.

2021-03-03 06:23 UTC, jonas054 commented
There are two distinct ways of using tab characters for indentation.

1. Use tabs with a width of 4 or 8 to save characters in a source code file. Tabs can be followed by spaces to reach the desired indentation level. There's no support in RuboCop for this way. For example,
```ruby
class MyClass
  def my_method
    @list.each do
      if x
< tab  >unless y
< tab  >  puts 'Yes'
< tab  >end
      end
    end
end
```
2. Use tab for indentation, no spaces, and necessarily one tab for one level of indentation. This is possible with RuboCop.
```ruby
class MyClass
<>def my_method
<><>@list.each do
<><><>if x
<><><><>unless y
<><><><><>puts 'Yes'
<><><><>end
<><><>end
<><>end
end
```
Using more than one tab per indentation level makes no sense. I think that adding validation so that `Layout/IndentationWidth` must be set to `1` if `EnforcedStyle` is `tabs`in `Layout/IndentationStyle` would solve the problem.

We should also change the comment `# Number of spaces for each indentation level` in `default.yml` to `# Number of spaces or tabs for each indentation level`.

2021-03-12 16:36 UTC, jonas054 requested changes
I think validating configuration is the way to go, rather than changing the autocorrect behavior. See comment.

2021-05-06 01:36 UTC, PikachuEXE commented
Seems incompatible with cop `Layout/DotPosition` when `EnforcedStyle: trailing`

2021-07-05 09:23 UTC, jonas054 commented
@PikachuEXE I'm not so sure that trailing dot position as any different than leading. The alignment with the first line for the chained method calls is just not possible when tabs are used for indentation.

For example, default configuration with spaces gives:
```ruby
unless y
       .z
  puts 'Yes'
end
```
while the configuration
```yaml
Layout/IndentationWidth:
  Width: 1

Layout/IndentationStyle:
  EnforcedStyle: tabs
```
results in:
```ruby
unless y
<><><><><><><>.z
<>puts 'Yes'
end
```
and with the addition of
```yaml
Layout/DotPosition:
  EnforcedStyle: trailing
```
we get
```ruby
unless y.
<><><><><><><>z
<>puts 'Yes'
end
```
The problem remains the same. Many cops that deal with alignment don't work well with tabs, and many times it's a problem that can't be solved unless we mix tabs and spaces, and then what's the point of using tabs?

2022-08-04 18:10 UTC, closed without merging