Fix `inherit_mode` for arrays in extension default
rubocop/rubocop pull request #9952
Opened 2021-07-25 14:48 UTC by pirj

See https://github.com/rubocop/rubocop-rspec/issues/1126

`config/default.yml`:
```yaml
RSpec:
  Language:
    Examples:
      inherit_mode:
        merge:
          - Regular
      Regular:
        - it
        - specify
        - example
        - scenario
        - its
```

`.rubocop.yml`:
```yaml
require:
  - rubocop-rspec

RSpec:
  Language:
    Examples:
      Regular:
        - mycustomexamplealias
```

Previously, locally-set `inherit_mode` in extension default configuration was not respected.

I'd love a preliminary review. If you're fine with the approach, I'll add a proper test coverage.

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [-] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [ ] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [ ] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

2021-07-25 18:52 UTC, pirj commented
@jonas054 Your solution to merging `inherit_mode` of derived and base is more elegant in [merge Exclude by default](https://github.com/rubocop/rubocop/pull/9624/files#diff-3aece4434e42e25fbf7122cef8f683d530df73a8b51a9e20dd87b0d981bafc9aR178). Do you want me to adjust this PR to use the same approach?

2021-07-25 19:14 UTC, pirj commented
Even though this is titled as a "fix", it might be considered a breaking change, too.

2021-07-27 15:59 UTC, bbatsov commented
The proposal seems reasonable to me, but I'll defer to @jonas054 on this one. As this affects only extensions and arguably the new behaviour is better I guess we don't have to label this a breaking change.

2021-07-27 16:06 UTC, dvandersluis commented
Thanks for fixing this @pirj!

I'm good with this not being a breaking change -- even if it does break a config, it is really a bug fix and that config shouldn't have worked in the first place.

Can we add some tests for the change?

2021-07-31 09:36 UTC, jonas054 requested changes
The code certainly looks good. Nice and readable. But I too would love to see some tests.

2021-08-03 05:37 UTC, bbatsov commented
@pirj Something seems off with the Win builds. Can you restart the build?

2021-08-03 07:56 UTC, pirj commented
@bbatsov All green.
Somehow it fixed itself, I didn't rebase on top of [the presumable fix](https://github.com/rubocop/rubocop/commit/b222b00c068b88bbd16e66e49f6a191fdd0b8aff).

2021-08-03 09:20 UTC, merged

2021-08-03 09:20 UTC, bbatsov commented
Thanks!

2021-08-03 15:17 UTC, jonas054 commented
:+1: